"""empty message

Revision ID: 18de6d262b95
Revises: a471153bb904
Create Date: 2025-01-31 16:52:58.593332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18de6d262b95'
down_revision = 'a471153bb904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('area_id', sa.Integer(), nullable=True))
    op.execute('UPDATE artist SET area_id = 1 WHERE area_id IS NULL')
    op.alter_column('venue', 'area_id', nullable=False)
    op.create_foreign_key(None, 'artist', 'areas', ['area_id'], ['id'])
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'area_id')
    # ### end Alembic commands ###
