"""empty message

Revision ID: 6428f7930941
Revises: 18de6d262b95
Create Date: 2025-01-31 17:00:03.730978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6428f7930941'
down_revision = '18de6d262b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
