from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6bf5a7152455'
down_revision = '6428f7930941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('artist_genres',
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.Column('genre_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
                    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
                    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
                    )
    op.create_table('venue_genres',
                    sa.Column('venue_id', sa.Integer(), nullable=False),
                    sa.Column('genre_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
                    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
                    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
                    )
    op.drop_column('artist', 'genres')
    op.add_column('venue', sa.Column(
        'seeking_description', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(),
                  nullable=False, server_default='http://example.com'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'seeking_description')
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(
        length=120), autoincrement=False, nullable=False))
    op.drop_table('venue_genres')
    op.drop_table('artist_genres')
    op.drop_table('genre')
    # ### end Alembic commands ###
